name: banking-platform

services:
  customer-postgres:
    image: postgres:18.4

    environment:
      POSTGRES_DB: ${CUSTOMER_DB_NAME}
      POSTGRES_USER: ${CUSTOMER_DB_USER}
      POSTGRES_PASSWORD: ${CUSTOMER_DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - customer-postgres-data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  customer-service:
    build:
      context: ..
      dockerfile: services/customer-service/Dockerfile

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://customer-postgres:5432/${CUSTOMER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${CUSTOMER_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${CUSTOMER_DB_PASSWORD}

    ports:
      - "8081:8081"

    depends_on:
      customer-postgres:
        condition: service_healthy

volumes:
  customer-postgres-data: