name: banking-platform

services:
  customer-postgres:
    image: postgres:18.4

    environment:
      POSTGRES_DB: ${CUSTOMER_DB_NAME}
      POSTGRES_USER: ${CUSTOMER_DB_USER}
      POSTGRES_PASSWORD: ${CUSTOMER_DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - customer-postgres-data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  customer-postgres-data: